language: ruby
dist: trusty
rvm:
  - 2.5
script: xvfb-run bundle exec rake
env:
  global:
    - BUNDLE_JOBS=4
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - qt5-default
      - libqt5webkit5-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-tools
      - gstreamer1.0-x
before_install:
  - gem install bundler -v '~> 1.17.3'
install:
  - bundle _1.17.3_ install --without production
